version: '3'

services:
  app:
    build: .
    ports:
      - 8081:8080
    volumes:
      - dev-maven-cache:/root/.m2
  mongo:
    image: mongo:5.0
  redis:
    image: redis:6

volumes:
  dev-maven-cache
