version: '3'

services:
  app:
    build: .
    user: quarkus
    volumes:
    - maven-cache:/home/quarkus/.m2
  mongo:
    image: mongo:5.0
  minio:
    image: minio/minio:latest
    command: server /data
  redis:
    image: redis:6

volumes:
  maven-cache:
    name: shared-maven-cache